# Generated by Django 4.2 on 2023-04-28 16:36

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    dependencies = [
        ('compraventa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to=pathlib.PurePosixPath('/home/debian/gualdapop/media')),
        ),
    ]
